--Creating Database
CREATE DATABASE LibraryDB
use LibraryDB
--Creating a table
USE LibraryDB
CREATE TABLE Books
(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR (50) NOT NULL,
Price INT
)


USE LibraryDB
GO
SELECT * FROM INFORMATION_SCHEMA.TABLES 
GO

SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME='Books'
